version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: driveform-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: driveform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - driveform-network

volumes:
  postgres_data:


networks:
  driveform-network:
    driver: bridge
